name: example
description: A simple command-line application.
environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  state_notifier:
  behavior_subject_mixin:
    path:
      ../
dev_dependencies:
  pedantic_mono:

