name: behavior_subject_mixin
description: A mixnin which provides stream of BehaviorSubject for StateNotifier.
version: 0.1.0
author: Ryunosuke Watanabe
homepage: https://github.com/HeavenOSK/behavior_subject_mixin
environment:
  sdk: '>=2.8.1 <3.0.0'
dependencies:
  rxdart: ^0.24.1
  state_notifier: ^0.5.0
dev_dependencies:
  pedantic_mono:
  test: ^1.14.4
