name: behavior_subject_mixin
description: A mixin which provides state of StateNotifier as a stream of BehaviorSubject.
version: 0.1.0
author: Ryunosuke Watanabe
homepage: https://github.com/HeavenOSK/behavior_subject_mixin
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  rxdart: ^0.24.1
  state_notifier: ^0.5.0
dev_dependencies:
  pedantic_mono:
  test: ^1.14.4
